all:
	gcc sender.c   -o sender.out   -Wall -Wextra -O2
	gcc receiver.c -o receiver.out -Wall -Wextra -O2

debug:
	gcc sender.c   -o sender.out   -Wall -Wextra -DDEBUG -g
	gcc receiver.c -o receiver.out -Wall -Wextra -DDEBUG -g
