all:
	gcc sender.c   -o sender.out   -Wall -Wextra
	gcc receiver.c -o receiver.out -Wall -Wextra

debug:
	gcc sender.c   -o sender.out   -Wall -Wextra -DDEBUG -g
	gcc receiver.c -o receiver.out -Wall -Wextra -DDEBUG -g
